name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  flutter_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.22.1"
          cache: true

      - name: Setup firebase
        env:
          DECRYPT_PASSWORD: ${{ secrets.ENC_PASS }}
        run: |
          openssl aes-256-cbc -pbkdf2 -d -in android/app/google-services.json.enc -out android/app/google-services.json -k "$DECRYPT_PASSWORD"
          openssl aes-256-cbc -pbkdf2 -d -in lib/firebase_options.dart.enc -out lib/firebase_options.dart -k "$DECRYPT_PASSWORD"
          openssl aes-256-cbc -pbkdf2 -d -in firebase.json.enc -out firebase.json -k "$DECRYPT_PASSWORD"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze --fatal-warnings

      - name: Build apk
        run: flutter build apk

      - name: Github Releases
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v0.0.${{github.run_number}}
          
